Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -48,11 +48,15 @@ jobs:
           echo "STATUS=Sanity Failed" >> $GITHUB_ENV
         fi
     - name: Swap Slots
-      if: contains(STATUS, 'Sanity Passed')
       run: |
-        az webapp deployment slot swap  -g openhackz6y6y8p2rg -n ${{ env.webapp_name }} --slot staging --target-slot production
-        echo "Slots Swapped"
-        curl https://openhackz6y6y8p2poi.azurewebsites.net/api/healthcheck/poi > /dev/null;if [ $? -eq 0 ];then echo "Passed"; else echo "Failed"; fi
+        if [[ $STATUS == 'Sanity Passed' ]]
+        then
+          az webapp deployment slot swap  -g openhackz6y6y8p2rg -n ${{ env.webapp_name }} --slot staging --target-slot production
+          echo "Slots Swapped"
+          curl https://openhackz6y6y8p2poi.azurewebsites.net/api/healthcheck/poi > /dev/null;if [ $? -eq 0 ];then echo "Passed"; else echo "Failed"; fi
+        else
+          echo "Sanity Failed and so not swapping Slots"
+        fi
     - uses: actions/github-script@0.9.0
       if: failure()
       with:
